### ISSUE TITLE
[Insight] Text files should end with a newline character - in .codeclimate.yml, line 19

### ISSUE THREAD

**Issue by rilwis** [rilwis/meta-box#1066]
**[in .codeclimate.yml, line 19](https://github.com/rilwis/meta-box/blob/ae08a76b537e10216ee4710db07011fff04bb7b7/.codeclimate.yml#L19)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
      standard: "WordPress"
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/7a16817b-61a8-4714-a3f2-bddfe15563ca/analyses/826)_
